[project]
name = "blinkit-mcp"
version = "1.0.1"
description = "Automate grocery shopping on Blinkit directly from Claude Desktop. Search, cart, and UPI payments."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["playwright", "mcp", "python-dotenv"]
